### PR TITLE
Fix wrong file in motd, better GRUB management, lots of formatting

### PR DESCRIPTION
**Pull request by dan-wittenberg**

### CODE REVIEW

**Comment by canihavethisone** [comment]
First test appear to show 2 issues, one critical, one not so critical:

Not so critical:
i. takes 2 runs to be idempotent, 1_6_1_1, 3_6_1 and 5_3_1 apply again on second run (3_6_1 and 5_3_1 also did this on previous release)

Critical:
ii. after a reboot with ip6 set to disabled, the ip6tables rules try to apply again and fail, then causing failed dependencies.  This probably need some nested logic to avoid?

I will do some more testing tonight.

**Comment by dan-wittenberg** [comment]
Yeah metadata and changleog are being bumped while merging, but I will see
what's up with the other two, thanks for testing!

**Comment by canihavethisone** [comment]
no problem.  This module is a great resource.

**Comment by dan-wittenberg** [comment]
I added a service definition to disable ip6tables, which can't be used if
ipv6 is disabled so we might as well avoid the errors.  I haven't looked at
5_3_1 code yet, and the others I don't see an easy fix, so it will require
a little more testing to get right.

**Comment by canihavethisone** [comment]
I seem to recall that I previously had issues with puppetlabs-firewall module if ipv6 is disabled at the kernel level, as it always tried to ensure the ip6tables service was enabled.  I found a param in the firewall code which I don't think was documented, something along the lines of 'ip6tables => false' or similar.  I can dig through the code later, and will also retest your changes in about 10 hours.  Unsure if this firewall issue is related to the bug above, as it wasn't a problem with previous builds of this module.

**Pull request merged**
