### PR TITLE
Minor bug fixes for CentOS8

### PR DESCRIPTION
**Pull request by tparkercbn**
- Fixed a caps problem
- Fixed the ensure_journal_ rules so that they can be disabled.

### CODE REVIEW

**Comment by bjvrielink** [comment]
- The fix for the capitalization of PATH in 6_2_3 is a good one. Thank you.
- Having a list of excluded rules on the agent system itself can be useful for audit evidence.
- There's no need for the dependency between the directory /usr/share/cis_scripts and the enforce_rules.txt as Puppet already has an auto-depends relationship between directories and files. Can you remove commit https://github.com/fervidus/secure_linux_cis/pull/62/commits/dc3a1d3e9d20eed01e4910b123390309f45710b8 from this PR?
- The $enforced parameter is a leftover from the 1.x version of this module. IMHO we should remove it from all rules, as we now have $exclude_rules and $include_rules. @bryanjbelanger what is your opinion on this?

**Comment by bryanjbelanger** [comment]
@prolixalias what are you thoughts on removing $enforced parameter now that we have $exclude_rules and $include_rules?

**Comment by tparkercbn** [comment]
The enforced parameter is very useful in mixed environments (Multiple OSes) that have those elements managed by in house modules.

Being able to disable a rule based on it’s name instead of its CIS number which seems to be per Operating system is a major advantage that this module has over others.

Please don’t remove that parameter.

Tom

**Comment by prolixalias** [comment]
> @prolixalias what are you thoughts on removing $enforced parameter now that we have $exclude_rules and $include_rules?

Having "enforced" compliments include/exclude and gives granularity that I think is important. Let's leave it.

**Comment by tparkercbn** [comment]
Thanks Bart.

I agree that there should be no need but for some reason without it on a completely clean system I was getting a directory doesn’t exist message.  I have no idea why as like you say there should be a dependency.

For the last bullet, I replied in a separate e-mail but the enforced param lets us disable rules based on name which is cross operating system and not dependant on the CIS number assigned.  In my case I have had to disable about 20 rules on my systems because those files are being managed by other modules and this way I don’t have to find and disable each rule for every operating system

Tom

**Comment by bjvrielink** [comment]
I understand the arguments about $enforced. I only would like to add that when you use this module with Foreman (or Red Hat Satellite), you cannot use the $enforced parameter, as Foreman only supplies values for parameters that are in classes that are directly included. That's why I'm a fan of the exclude_rules and include_rules approach and overlooked the value of $enforced.

**Comment by tparkercbn** [comment]
Hello. I'm not super good with git.  How can I do this: 

"There's no need for the dependency between the directory /usr/share/cis_scripts and the enforce_rules.txt as Puppet already has an auto-depends relationship between directories and files. Can you remove commit dc3a1d3 from this PR?"

Tom

**Comment by tparkercbn** [comment]
I'm going to close this pull request and create a few smaller ones with each fix

**Pull request closed without merging**
