### PR TITLE
Create resource collector override to disable ip6tables

### PR DESCRIPTION
**Pull request by canihavethisone**
…in class cis_3_3_3 when ipv6 disabled.  Change default of ip6_enabled to false (ipv6 is now now opt-in).
Update fixtures, changelog and metadata.

### CODE REVIEW

**Comment by canihavethisone** [comment]
so, title == can be used instead of tag ==, and in this module they both seem to work.  I am looking into the difference.

**Comment by canihavethisone** [comment]
no, the sysctl entries fail to apply if the Kernel parameter has be set first and a reboot occurs.  I have actually put the sysctl entries back now as they apply as long as a reboot hasn't yet occured.

**Comment by canihavethisone** [comment]
started running shellcheck over bash scripts and verifying functions

**Comment by bryanjbelanger** [comment]
Hey @canihavethisone , @dan-wittenberg and I are wondering if we will see you at PDX in October.

You planning on coming?

**Comment by canihavethisone** [comment]
No I won't make it this year.

**Pull request merged**
