### PR TITLE
Added 4_1_12, improved 5_4_1_4, 3_4_2 and 3_4_3

### PR DESCRIPTION
**Pull request by bjvrielink**
- Added a new fact for files to audit (4_1_12)
- Added code to implement 5_4_1_4 for new users (useradd default)
- Add new line to /etc/hosts.{allow,deny} (or else ssh complains about this in syslog)

### CODE REVIEW

**Comment by canihavethisone** [comment]
@bjvrielink can I make a few request and suggestions before this is merged please:

1. Please update Metadata and changelog, incrementing the release number
2. I suggest using the file-line resource to manage the INACTIVE entry instead as it should be less intensive, ie
`    # Set default inactive days for new users
    file_line {'useradd_inactive':
      ensure => present,
      path   => '/etc/default/useradd',
      line   => "INACTIVE=$pass_inactive_days",
      match  => '^#?INACTIVE=',
    }`
3. Can you please broaden the range for puppetlabs/firewall in metadata, puppet file and fixtures as I have had issues when combining this module with some others that have a limitation of < 2.0.0, ie
`    {
      "name": "puppetlabs/firewall",
      "version_requirement": ">= 1.15.0 < 3.0.0"
    },`

Cheers.

**Comment by bjvrielink** [comment]
> @bjvrielink can I make a few request and suggestions before this is merged please:
> 
>     1. I suggest using the file-line resource to manage the INACTIVE entry instead of shellvar as it may be less intensive, ie
>        # Set default inactive days for new users
>        file_line {'useradd_inactive':
>        ensure => present,
>        path   => '/etc/default/useradd',
>        line   => "INACTIVE=$pass_inactive_days",
>        match  => '^#?INACTIVE=',
>        }
> 
>     2. Importantly, can you please broaden the range for puppetlabs/firewall in metadata, puppet file and fixtures as I have had issues when combining this module with some others that have a limitation of < 2.0.0, ie
>        {
>        "name": "puppetlabs/firewall",
>        "version_requirement": ">= 1.15.0 < 3.0.0"
>        },
> 
>     3. Please update Metadata and changelog and increment the release number.  I was preparing a pull request with:
>        Release 1.0.16
> 
> 
>     * Add file_line management of /etc/default/useradd INACTIVE entry in cis_5_4_1_4 to meet Nessus scan requirement
> 
>     * Expand puppetlabs/firewall version range to >= 1.15.0 < 3.0.0 as many other modules still have < 2.0.0 and this module will fail to install
> 
> 
> Cheers.

Made the updates. Originally I did not update metadata & changelog as that is something I would expect to be done at time of making a release of the module to the forge, something I lack the capabilities to do...

**Comment by canihavethisone** [comment]
Thank you.  In my workflow I like to make the changelog and metadata changes within a pull request to save the publisher effort and ensure that the changelog reflects what was done by the author.  Perhaps @bryanjbelanger can indicate if he prefers that to be done or not.

One issue I still see with this module is the way that augeus is used in mount_options.pp.  Specifically, if a volume has an fsoption of 'exec', when it is processed to be 'noexec' the option is appended, not replaced.  While fstab only applies the last option in the chain (ie the 'exec' then gets ignored) it would be great to have this process result in a cleaner fstab entry, keeping in mind that any other options need to be preserved if they are not being managed/changed.  So far I haven't got that working without considering using awk, and my augeus isn't strong. Not a big deal but one I have identified.

**Comment by canihavethisone** [comment]
I am testing these changes and so far I see a few issues:
1. the changes to /etc/hosts.allow and /etc/hosts.deny so not appear to actually add a new line to the file
2. the adding of new audit rules in cis_4_1_12 could best be done in accordance with the other audit.rules as managed in surrounding classes so the rule changes write directly to /etc/audit/rules.d/audit.rules and trigger a reboot to take effect (if reboot is opted in), and use the same logic, ie:

      file_line { 'audit.rules privileged access':
        ensure => present,
        path   => '/etc/audit/rules.d/audit.rules',
        line   => $facts['audit_privileged'],
      }

Interestingly, although the fact returns multiple lines, the file_line resource appears to work OK

**Comment by bjvrielink** [comment]
Sorry for the confusion, as there is a subtle difference between 'new line' and 'newline'. I meant these should add a newline character to /etc/hosts.allow and /etc/hosts.deny.

In the auditd systemd unit file there is  a ExecStartPost=-/sbin/augenrules --load.
augenrules takes care of merging the various files in /etc/audit/rules.d into /etc/audit/audit.rules and will sort the '-e 2' rule to the end of the file. /etc/audit/audit.rules is the file that actually is used by auditd (or it should be...)
You already noticed the side effects of file_line. This is why I chose to use this approach.

**Comment by canihavethisone** [comment]
I may need to do some more testing, however it appears that as cis_4_2_18 adds '-e 2' to audit.rules it makes that file immutable and therefore the additional rules in the proposed cis_4_1_12 never get written to that file (upon reboot) and have no effect.

**Comment by bjvrielink** [comment]
cis_4_1_18 adds the '-e 2' line to /etc/audit/rules.d/audit.rules, not to /etc/audit/audit.rules. augentool is responsible to add all lines in /etc/audit/rules.d/* to /etc/audit/audit.rules and trigger auditctl to load whatever is in /etc/audit/audit.rules into the auditd.

N.B. The name /etc/audit/rules.d/audit.rules is a bit confusing, a more sensible name would be /etc/audit/rules.d/cis.rules

**Comment by bjvrielink** [comment]
I could add cis_4_1_12 to the list of classes requiring a reboot, but if $auto_restart is true, then any user can trigger a reboot of the system...

CIS 4.1.12 demands that any file that is setuid or setgid to be audited, not just files owned by root. As any ordinary user can create a setuid file, any user trigger a reboot if cis_4_1_12 is added to the    $restart_classes  variable, just by doing a chmod 4000 on one of their own files.

**Comment by canihavethisone** [comment]
You are correct.  Sorry I was indeed confusing /etc/audit/rules.d/audit.rules and /etc/audit/audit.rules.  I recall the intention at one stage was to write directly to /etc/audit/audit.rules so the rules could take effect without reboot.  What are your thoughts on doing this, or otherwise renaming the /etc/audit/rules.d/audit.rules to cis.rules?

Regarding having cis_4_1_12 among the array of classes triggering an opt-in reboot, I am in 2 minds about this.  I guess the main thing is that a reboot will get triggered after the initial run.  Another thought is to trigger a notice when cis_4_1_12 makes a change informing that it won't take effect until a reboot.

**Comment by canihavethisone** [comment]
@bjvrielink I  have just noticed that the update to firewall range in metadata you added is "version_requirement": ">= 1.5.0 < 3.0.0", not "version_requirement": ">= 1.15.0 < 3.0.0".  Could you please amend it to 1.15.x?  In fact as I only want to keep it under 2.x.x it could actually be "version_requirement": ">= 1.15.3 < 3.0.0".

Thanks.

**Comment by bjvrielink** [comment]
I will rename to cis.rules next time I'm in a refactoring mood. For existing users of this module this of course means that there is an audit.rules file already in place that is no longer maintained by Puppet.

Personally, I'm not a fan of doing automatic reboots by Puppet. It looks like this feature was implemented in this module with the first Puppet run that hardens the system in mind, but the reboot can happen each half hour, if any of the conditions change. A notice may be a good compromise, but I'd have to figure out exactly how to implement it. Each time the /etc/audit/rules.d/cis_4_1_12.rules file resource changes, a reboot would be required, but one cannot simply subscribe a notify to that resource because:
- it would also trigger the first time Puppet is run (not really an issue as the chance that the file changed then is close to 100%)
- It would only trigger the first run when the file did change, not on consequent runs.
I could also export the timestamp of this file as a fact. If that is higher than the time of reboot, then trigger a notice. I'm not sure it is the most elegant solution, but certainly not the worst I can come up with :)

During a Puppet run, the client first downloads/updates the custom facts, then runs these facts and uploads the results, and after that the server compiles the catalog (based on the most recent facts) and this catalog is used. So the contents of /etc/audit/rules.d/cis_4_1_12.rules are based on information that is only a few seconds old.

**Comment by canihavethisone** [comment]
Agreed.  Leaving cis_4_1_12 out of the reboot array makes sense as it is really the only rule likely to change.  The reboot is opt-in with a default of false for other audit classes.  Thank you for correcting the firewall range.

**Pull request merged**
