### PR TITLE
change sysctl to file_line resource as fails after reboot with kernel_parameter

### PR DESCRIPTION
**Pull request by canihavethisone**
in cis_3_3_1, cis_3_3_2 and cis_3_3_3.  Issue is that kernel_parameter ipv6.disable=1 prevents the creation of /proc/sys/net/ipv6 and therefore sysctl module fails (even when apply param is set to false)
Fixed type in cis_5_2_14
Finished refactoring bash scripts.

This merge request seems odd as its showing old commits and a conflict - let me know if I need to fix something.

### CODE REVIEW

**Comment by canihavethisone** [comment]
Can I pls get some help refactoring mount_options.pp so it works better with Centos?  It appears that Augeas fails if the entry isn't already in /etc/fstab, and 1.1.17 for example cannot be applied when trying to add /dev/shm, and is currently commented out of centos7.pp

**Comment by dan-wittenberg** [comment]
Yeah I'll take a look

**Comment by canihavethisone** [comment]
That's a good point.  It could be moved outside the if statement which would then always create the resource.  I'll give it a test.

**Comment by canihavethisone** [comment]
I have moved the exec['reload rsyslog'] to both centos7.pp and redhat7.pp in a new 'shared resources' block at the end of both files.  I have also added an entry for puppetlabs/reboot (and to metadata/fixtures/puppetfile) as this should be notified by such classes as those that make changes to audit.rules and set kernel_parameter, as these changes require a reboot to take effect.  I have NOT yet set those notifies however.

The changes in this pull request get Nessus L1 & L2 scan AFTER a reboot down to:
- 345 passed
- 30 failed

- 28 of the fails are ignorable (eg FAT filesystem active as I am using EFI, grub.cfg/user.cfg 0700 in EFI mount not catered for, banner entries, not restricted root to console only, the way that Nessus greps some files etc)
- 1 can be fixed if the /dev/shm noexec requirement is addressable by mount_options.pp changes
- 1 or 2 require further consideration investigation eg, /var/log/btmp and wtmp have group owner utmp, and Nessus wants it to be root group

**Comment by canihavethisone** [comment]
I have also added a shared block to reload sshd config only if sshd service is already running, and only when notified by the cis_5_2_x series of classes that managed sshd_config entries

**Comment by canihavethisone** [comment]
Agreed.  I have added a default path for execs.

**Comment by canihavethisone** [comment]
@bryanjbelanger can you please review and merge these changes as I have completed the refactoring that I had wanted to include.  One remaining point for consideration is if pkill should be used at all (as it currently is with rsyslog) as it is prudent to protect a host from critical services such as rsyslog, auditd etc being terminated and this can result in the host being rebooted into single mode or shutdown (hence the introduction of an opt-it reboot feature).  If you agree with that then I can quickly remove the pkill usage and add those classes to the auto_restart optional array.

**Pull request merged**
