### PR TITLE
Added exclude_logs to the ensure_permissions_on_all_logfiles_are_configured

### PR DESCRIPTION
**Pull request by tparkercbn**
rule to ignore certain files (generally ones managed by other modules)

### CODE REVIEW

**Comment by bjvrielink** [comment]
Looks like a good addition to have, and something I also could use for my own environment. But, as it is written now, I cannot take advantage of it, as in Foreman you cannot specify parameters for classes that are not directly included by Foreman. If instead of $exclude_logs this rule uses $secure_linux_cis::exclude_logs, this improvement can also be used together with Foreman.

**Comment by tparkercbn** [comment]
I can make that change.  Are there any other modules that should use the same array?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bjvrielink** [comment]
Thank you.

I don't think there are many other classes that use "local" parameters. I could only find ensure_only_strong_ciphers_are_used.pp, ensure_bootloader_password_is_set.pp, ensure_x_window_system_is_not_installed.pp, ensure_only_strong_key_exchange_algorithms_are_used.pp and of course $enforced.

$enforced should be left as is. Exposing that via the main class adds too much code for not much gain. It would be nice if those other 4 classes were changed to use the $secure_linux_cis:: style parameters, but not just because we can; changing it could break this module for those that happen to use the existing parameters.

**Comment by tparkercbn** [comment]
There is a way to make the module default to the main variable so that people’s existing code won’t break.

I will make those changes in a single PR, leave the local variables where they are but default them to main class variables.

Does that make sense?

Tom

**Comment by bjvrielink** [comment]
Something like:

```class secure_linux_cis::rules::ensure_permissions_on_all_logfiles_are_configured(
    Array[Stdlib::Unixpath] $exclude_logs = $secure_linux_cis::exclude_logs,
```

?

**Comment by tparkercbn** [comment]
Exactly what I was planning to do.  Then if people have it in hiera or in a class param it will take their value otherwise defalt to the main class value which we can set to a sane default

Tom

**Comment by bjvrielink** [comment]
Go ahead with the PR, either for just ensure_permissions_on_all_logfiles_are_configured, or also include the 4 others I've found. Let me know if I can help.

**Comment by tparkercbn** [comment]
Will do.  It should be quick to do all 4

Tom

**Comment by tparkercbn** [comment]
I added the parm for the exclude logs to this PR.  I will update the other ones as a separate PR (or would you prefer one PR per rule?)

**Pull request merged**
